# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: NextGenPSD2 Reference Toolkit Documentation
site_description: Documentation for NextGenPSD2 Reference Toolkit
site_author: WSO2
site_url: https://berlin.ob.docs.wso2.com/en/latest/

# Repository
repo_name: wso2/docs-ob-toolkit-berlin
repo_url: https://github.com/wso2/docs-ob-toolkit-berlin
edit_uri: https://github.com/wso2/docs-ob-toolkit-berlin/edit/main/en/docs/

# Copyright
copyright: NextGenPSD2 Reference Toolkit - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'

# Navigation
nav:
  - 'Home': index.md
  - 'Get Started':
    - 'Open Banking': get-started/open-banking.md
    - 'Open Banking Requirements': get-started/open-banking-requirements.md
    - 'Regulations and Standards': get-started/regulations-and-standards.md
    - 'NextGenPSD2 Reference Toolkit': get-started/wso2-open-banking-berlin-toolkit.md
    - 'About this Release': get-started/about-this-release.md
    - 'Quick Start Guide':
      - 'Get Started': get-started/quick-start-guide.md
      - 'Set up Toolkits': get-started/set-up-toolkits.md
      - 'Configure Users and Roles': get-started/configure-users-and-roles.md
      - 'Configure IS as Key Manager': get-started/configure-is-as-key-manager.md
      - 'Deploy API': get-started/deploy-api.md
      - 'TPP Onboarding': get-started/tpp-onboarding.md
      - 'Tryout Flow': get-started/try-out-flow.md
  - 'Install and Setup':
    - 'Prerequisites': install-and-setup/prerequisites.md
    - 'Setting up servers': install-and-setup/setting-up-servers.md
    - 'Setting up databases': install-and-setup/setting-up-databases.md
    - 'Configuring Identity Server': install-and-setup/configuring-identity-server-for-ob.md
    - 'Configuring API Manager': install-and-setup/configuring-api-manager-for-ob.md
    - 'Configuring Users and Roles': install-and-setup/configuring-users-and-roles.md
    - 'Upgrading the solution': install-and-setup/upgrading-the-solution.md
      #- 'Upgrading the solution': install-and-setup/upgrading-the-solution/upgrading-the-solution.md
      #- 'Upgrading to API Manager 3.2.0': install-and-setup/upgrading-the-solution/upgrading-wso2-api-manager-320.md
      #- 'Upgrading to Identity Server 5.11.0': install-and-setup/upgrading-the-solution/upgrading-wso2-identity-server.md
      #- 'Upgrading to API Manager 4.0.0': install-and-setup/upgrading-the-solution/upgrading-wso2-api-manager-400.md
      #- 'Open Banking Data Migration': install-and-setup/upgrading-the-solution/open-banking-data-migration.md
      #- 'Modifications After Migration': install-and-setup/upgrading-the-solution/modifications-after-migration.md
  - 'Learn':
    - 'Consent Management':
       - 'Introduction': learn/consent-management.md
       - 'Consent Manager': learn/consent-manager.md
    - 'Consent Authorization': learn/consent-authorization-intro.md
    - 'Token Authentication': learn/token-authentication.md
    - 'TPP Onboarding':
       - 'Introduction': learn/tpp-onboarding.md
       - 'Configuration': learn/tpp-onboarding-configuration.md
    - 'Strong Customer Authentication':
       - 'Introduction': learn/strong-customer-authentication.md
       - 'Configuration': learn/strong-customer-authentication-configuration.md
    - 'API Security':
       - 'Introduction': learn/api-security.md
       - 'Configuration': learn/api-security-configuration.md
    - 'Integration with Bank': learn/integration-with-bank.md
  - 'Try out':
    - 'Deploy NextGenPSD2XS2A API': try-out/deploy-nextgenpsd2-api.md
    - 'TPP Onboarding': try-out/tpp-onboarding.md
    - 'Account Information Service Flow': try-out/account-information-service-flow.md
    - 'Payment Initiation Service Flow': try-out/payment-initiation-service-flow.md
    - 'Confirmation of Funds flow': try-out/confirmation-of-funds-flow.md
    - 'Consent Manager': try-out/consent-manager.md
  - 'References':
    - 'Identity Server Configuration Catalog': references/config-catalog-is.md
    - 'API Manager Configuration Catalog': references/config-catalog-apim.md
    - 'Consent REST API': references/consent-rest-api.md
    - 'DCR REST API': references/dcr-rest-api.md
    - 'Application Info API': references/application-info-api.md
  - '': page-not-found.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
#plugins:
#  - search
##  - markdownextradata: {}
#  - redirects:
#      redirect_maps:
#        'install-and-setup/upgrading-the-solution/upgrading-the-solution.md': 'https://berlin.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'
#        'install-and-setup/upgrading-the-solution/upgrading-wso2-api-manager-320.md': 'https://berlin.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'
#        'install-and-setup/upgrading-the-solution/upgrading-wso2-identity-server.md': 'https://berlin.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'
#        'install-and-setup/upgrading-the-solution/upgrading-wso2-api-manager-400.md': 'https://berlin.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'
#        'install-and-setup/upgrading-the-solution/open-banking-data-migration.md': 'https://berlin.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'
#        'install-and-setup/upgrading-the-solution/modifications-after-migration.md': 'https://berlin.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'

# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 1.0.0
  nav_list:
    - Home
    - Get Started
    - Install and Setup
    - Learn
    - Try out